import './style.css';
import {createStage} from './stage.js';
import {createAudio} from './audio.js';
import {chapters,people,gestures,initial,input,advance,exchange,ruleProposal,validProposal,accept} from './score.js';
const $=q=>document.querySelector(q),params=new URLSearchParams(location.search),pad=params.get('audience');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=initial(),stage,proposal=null,busy=false,demoTimers=[],view='rehearsal',apiStatus=null;const audio=createAudio();
const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/audience`);
if(pad&&people.some(p=>p.id===pad)){
 $('#app').innerHTML=`<main class="pad"><div class="eyebrow">BEFORE WAKING / AUDIENCE ${pad}</div><h1>让这个下午<br>感受到你。</h1><p>独立观众输入页 · 与同一服务的排练页连接</p><div class="pad-buttons">${Object.entries(gestures).map(([k,v])=>`<button data-pad="${k}">${v}</button>`).join('')}</div><p id="pad-status">正在连接…</p><a href="/">返回舞台</a></main>`;
 ws.onopen=()=>$('#pad-status').textContent='已连接 · 动作将发送至舞台';ws.onclose=()=>$('#pad-status').textContent='连接断开，请刷新';document.querySelectorAll('[data-pad]').forEach(b=>b.onclick=()=>{if(ws.readyState===1){ws.send(JSON.stringify({type:'gesture',who:pad,kind:b.dataset.pad}));$('#pad-status').textContent=`已发送：${gestures[b.dataset.pad]}`;}});
}else{
 $('#app').innerHTML=`<div class="shell"><div id="viewport"></div><div class="vignette"></div>
 <header><div class="brand"><span class="brand-mark">◌</span><div><strong>醒来之前</strong><small>BEFORE WAKING</small></div></div><nav><button data-view="immersive">沉浸观看</button><button data-view="rehearsal" class="active">排练控制</button><button data-view="layout">舞台布局</button></nav><span class="edition">STUDY 01 <i></i> 共振排练室</span></header>
 <section class="scene-caption"><div class="eyebrow" id="chapter-number">00 / 一段共同的梦</div><h1 id="scene-title">一个停住的下午</h1><p id="scene-line">姥爷。你听得见吗？</p><div class="scene-note" id="scene-note">拖动视角 · 滚轮调整距离</div></section>
 <aside class="panel"><div class="panel-title"><span>现场 / LIVE SCORE</span><span id="pause-badge">运行</span></div><p id="hint" class="hint"></p>
 <div class="section-label">01　选择一个身体</div><div class="people">${people.map(p=>`<button data-person="${p.id}" style="--person:${p.color}"><i></i>${p.id}<span id="count-${p.id}">0</span></button>`).join('')}</div>
 <div class="gesture-grid">${Object.entries(gestures).map(([k,v],i)=>`<button data-gesture="${k}"><span>${v}</span><small>${['SPACE','W','S','H','J','C'][i]}</small></button>`).join('')}</div><div class="participant-note">电脑模拟身体输入 · 1–4 切换观众<br><a id="pad-link" href="/?audience=A" target="_blank">打开 A 的独立输入页 ↗</a></div>
 <div class="section-label">02　演员决定下一步</div><div class="actor-controls"><button id="approach">向他靠近</button><button id="exchange">交换小熊</button><button id="next" class="primary">下一节拍 →</button><button id="pause">暂停 / HOLD</button></div>
 <div class="section-label">03　让刚才的动作回来</div><div class="ai-mode"><button id="rules-mode" class="active">规则对照</button><button id="ai-mode">真实 AI</button></div><label class="observation-label" for="observation">操作员观察（可选）</label><select id="observation-kind" aria-label="观测动作类型">${Object.entries(gestures).map(([k,v])=>`<option value="${k}" ${k==='sleeve'?'selected':''}>${v}</option>`).join('')}</select><input id="observation" maxlength="160" placeholder="例如：A 反复给小熊拉直左袖"><button id="observe" class="text-button">记录到当前观众</button><button id="propose" class="wide">准备一条共振提议</button><div id="ai-status" class="micro">正在检查 AI 连接…</div><div id="proposal" class="proposal empty">先让一个动作发生。<br>它可以在后面的照顾中回来。</div>
 <details><summary>本场留下的痕迹 <span id="event-count">0</span></summary><div id="event-log"></div><button id="export" class="text-button">导出本场记录</button></details>
 </aside>
 <footer><div class="transport"><button id="sound" title="声音">声音 开</button><button id="reset">重新开始</button><button id="demo-warm">热烈一场 · 90s</button><button id="demo-quiet">安静一场 · 90s</button><span id="demo-status"></span></div><div class="score">${chapters.map((c,i)=>`<button data-chapter="${i}"><b>0${i+1}</b><span>${['黑暗','金光','太阳雨','追赶','交换','照顾'][i]}</span><i></i></button>`).join('')}</div><div class="footnote"><span id="callback-status">每个动作，都可能在另一个世界被记起。</span><span>真人动作的数字占位 · 实体升降未接入</span></div></footer>
 <div id="toast" role="status"></div><div id="start" class="start"><div class="start-card"><div class="eyebrow">一间房 · 两个世界 · 四个身体</div><h1>醒来之前</h1><p>他看不见我们。<br>但他的手，还记得怎样照顾一只小熊。</p><button id="enter">进入这个下午 <span>↗</span></button><small id="loading">正在载入 Blender 舞台资产…</small></div></div>
 </div>`;
 function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
 function refresh(){const c=chapters[state.chapter];$('#chapter-number').textContent=`0${state.chapter+1} / 六个可以停留的节拍`;$('#scene-title').textContent=c.title;$('#scene-line').textContent=c.line;$('#hint').textContent=c.hint;$('#pause-badge').textContent=state.paused?'暂停':'运行';$('#pause').textContent=state.paused?'继续 / RESUME':'暂停 / HOLD';$('#pause-badge').classList.toggle('hold',state.paused);
 document.querySelectorAll('[data-chapter]').forEach(b=>b.classList.toggle('active',+b.dataset.chapter===state.chapter));document.querySelectorAll('[data-person]').forEach(b=>b.classList.toggle('active',b.dataset.person===state.selected));people.forEach(p=>$('#count-'+p.id).textContent=state.events.filter(e=>e.who===p.id).length);$('#event-count').textContent=state.events.length;$('#event-log').innerHTML=state.events.slice(-8).reverse().map(e=>`<div><b>${e.who}</b><span>${esc(gestures[e.kind])}${e.note?' · '+esc(e.note):''}</span><small>${e.id}</small></div>`).join('');$('#pad-link').textContent=`打开 ${state.selected} 的独立输入页 ↗`;$('#pad-link').href='/?audience='+state.selected;
 $('#approach').disabled=state.chapter!==3||state.paused;$('#exchange').disabled=state.chapter!==4||state.exchanged||state.paused;$('#exchange').textContent=state.exchanged?'已经交换':'交换小熊';$('#next').disabled=state.chapter===5||state.paused||(state.chapter===4&&!state.exchanged);$('#rules-mode').classList.toggle('active',state.mode==='rules');$('#ai-mode').classList.toggle('active',state.mode==='ai');$('#propose').disabled=busy||state.paused||!state.events.length;
 $('#scene-note').textContent=view==='layout'?'真实演员与椅子固定；窗外和房间外层为数字影像。':'拖动视角 · 滚轮调整距离';
 }
 function changeChapter(n){if(state.paused)return;state.chapter=n;state.epoch++;state.accepted=null;proposal=null;showProposal();audio.chapter(n);refresh();}
 function receive(who,kind,note=''){if(!state.started)return;const e=input(state,who,kind,note);if(!e)return;stage?.gesture(e);audio.gesture(kind);if(state.chapter===0&&kind!=='call')changeChapter(1);if(state.chapter===1&&state.events.filter(e=>e.kind!=='call').length>=6)changeChapter(2);refresh();}
 ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='gesture')receive(m.who,m.kind);}catch{}};
 function emit(kind){if(ws.readyState===1)ws.send(JSON.stringify({type:'gesture',who:state.selected,kind}));else receive(state.selected,kind);}
 function showProposal(){const box=$('#proposal');if(!proposal){box.className='proposal empty';box.innerHTML='先让一个动作发生。<br>它可以在后面的照顾中回来。';return;}box.className='proposal';box.innerHTML=`<div class="proposal-source">${esc(proposal.provider==='rules'?'规则对照':proposal.provider)} · ${esc(proposal.who)} / ${esc(proposal.sourceEvent)}</div><h3>${esc(proposal.title)}</h3><p>${esc(proposal.actorCue)}</p><p class="micro">${esc(proposal.visualCue)}</p><p class="reason">${esc(proposal.reason)}</p><div class="proposal-actions"><button id="accept">接住这个动作</button><button id="reject">暂不采用</button></div>`;$('#accept').onclick=()=>{if(!accept(state,proposal)){notify('提议已过期或演出暂停，请重新准备');return;}stage.callback(proposal);audio.callback();$('#callback-status').textContent=`${proposal.who} 的动作正在回来：${proposal.actorCue}`;notify('已接纳 · 局部光线回调，演员可接续建议');proposal=null;showProposal();refresh();};$('#reject').onclick=()=>{proposal=null;showProposal();notify('演员保留当前演法');};}
 async function propose(){if(busy||state.paused||!state.events.length)return;if(state.mode==='rules'){proposal=ruleProposal(state);showProposal();return;}busy=true;$('#ai-status').textContent='AI 正在观察本场动作；舞台继续运行…';refresh();const epoch=state.epoch;try{const r=await fetch('/api/propose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({epoch,chapter:chapters[state.chapter].id,events:state.events,responded:state.callbacks.map(c=>c.who)})});const p=await r.json();if(!r.ok)throw Error(p.error);if(!validProposal(state,p)){notify('段落已改变：迟到的AI提议已丢弃');$('#ai-status').textContent='过期提议已丢弃，当前演出保持不变';return;}proposal=p;showProposal();$('#ai-status').textContent=`真实生成 · ${p.provider} · ${(p.latencyMs/1000).toFixed(1)}秒`;}catch(e){$('#ai-status').textContent=e.message;notify('AI 暂不可用，规则对照仍可继续');}finally{busy=false;refresh();}}
 function stopDemo(){demoTimers.forEach(clearTimeout);demoTimers=[];$('#demo-status').textContent='';}
 function reset(){stopDemo();const epoch=state.epoch+1,started=state.started,mode=state.mode;state={...initial(),epoch,started,mode};proposal=null;stage?.reset();showProposal();$('#callback-status').textContent='每个动作，都可能在另一个世界被记起。';refresh();}
 function runDemo(quiet){reset();state.started=true;audio.init();$('#start').classList.add('hidden');$('#demo-status').textContent='模拟观众 · '+(quiet?'安静路径':'热烈路径');const schedule=(ms,fn)=>demoTimers.push(setTimeout(()=>{if(!state.paused)fn();},ms));for(let i=0;i<24;i++)schedule(1500+i*1700,()=>receive(people[i%4].id,quiet?['sway','hug','sleeve','sing'][i%4]:['stomp','stomp','sway','sing','call'][i%5]));schedule(44000,()=>changeChapter(3));for(let i=0;i<4;i++)schedule(48000+i*2500,()=>{state.approaches++;refresh();});schedule(62000,()=>changeChapter(4));schedule(69000,()=>{exchange(state);refresh();});schedule(75000,()=>changeChapter(5));schedule(79000,()=>{proposal=ruleProposal(state);showProposal();if(proposal){accept(state,proposal);stage.callback(proposal);audio.callback();$('#callback-status').textContent=`${proposal.who} 的${gestures[state.events.find(e=>e.id===proposal.sourceEvent)?.kind]}回到照顾里（规则模拟）`;}});schedule(90000,()=>{$('#demo-status').textContent='模拟演绎完成 · 可以继续停留';});}
 document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.person;refresh();});document.querySelectorAll('[data-gesture]').forEach(b=>b.onclick=()=>emit(b.dataset.gesture));document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{stopDemo();changeChapter(+b.dataset.chapter);});
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.body.dataset.view=view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));stage?.setView(view==='layout'?'layout':view==='immersive'?'close':'audience');refresh();});
 $('#enter').onclick=()=>{if(!stage)return;state.started=true;audio.init();$('#start').classList.add('hidden');refresh();};$('#next').onclick=()=>{stopDemo();if(advance(state)){proposal=null;showProposal();audio.chapter(state.chapter);refresh();}};$('#pause').onclick=()=>{state.paused=!state.paused;if(state.paused){stopDemo();notify('暂停了当前演出，自动演绎已停止');}refresh();};$('#approach').onclick=()=>{state.approaches++;refresh();};$('#exchange').onclick=()=>{if(exchange(state)){audio.callback();notify('小熊已经交换。让照顾慢慢发生。');refresh();}};$('#reset').onclick=reset;$('#demo-warm').onclick=()=>runDemo(false);$('#demo-quiet').onclick=()=>runDemo(true);
 let muted=false;$('#sound').onclick=()=>{muted=!muted;audio.mute(muted);$('#sound').textContent='声音 '+(muted?'关':'开');};$('#rules-mode').onclick=()=>{state.mode='rules';refresh();};$('#ai-mode').onclick=()=>{state.mode='ai';refresh();};$('#propose').onclick=propose;$('#observe').onclick=()=>{const note=$('#observation').value.trim();if(note){receive(state.selected,$('#observation-kind').value,note);$('#observation').value='';}};
 $('#export').onclick=()=>{const data={title:'醒来之前',version:'0.1',createdAt:new Date().toISOString(),inputMode:'manual/simulated—not camera recognition',state};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='before-waking-rehearsal.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if(!state.started)return;const id={'1':'A','2':'B','3':'C','4':'D'}[e.key];if(id){state.selected=id;refresh();}const kind={' ':'stomp',w:'sway',s:'sing',h:'hug',j:'sleeve',c:'call'}[e.key.toLowerCase()];if(kind&&!e.repeat){e.preventDefault();emit(kind);}});
 fetch('/api/status').then(r=>r.json()).then(s=>{apiStatus=s;$('#ai-status').textContent=s.available?`可用：${s.model} · 点击提议时才调用`:'AI未配置 · 规则对照可完整演出';}).catch(()=>$('#ai-status').textContent='AI连接检查失败');
 refresh();createStage($('#viewport'),()=>state).then(s=>{stage=s;$('#loading').textContent='资产已就绪 · 建议打开声音';$('#enter').classList.add('ready');}).catch(e=>{$('#loading').textContent='舞台载入失败：'+e.message;console.error(e);});
}
